# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COgZDWDO-SXffhp6GerEHbIc4yQ-7YbR
"""

# For reading data
import os
import gc
import numpy as np
from xml.dom import minidom

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# For visualizing
import plotly.express as px
from torchvision.io import read_image
from torchvision import tv_tensors
from torchvision.transforms.v2 import functional as F

# For model building
import torch
import torch.nn as nn
import torchvision
from torchvision.models.detection import FasterRCNN
#from torchvision.models.detection.rpn import AnchorGenerator

# for videos
import cv2 as cv



#define nn

BaseballNN = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")

def collate_fn(batch):
    return tuple(zip(*batch))


params = [p for p in BaseballNN.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(
    BaseballNN.parameters(),
    lr=0.005,
    momentum=0.9,
    weight_decay=0.0005
)

# construct an optimizer


# let's train it just for 2 epochs
num_epochs = 1

#backbone = torchvision.models.mobilenet_v2(weights="DEFAULT").features
    #mobilenet_v2 output channels are 1280
#backbone.out_channels = 1280

            
    # RPN generate 5 x 3 anchors per spatial location, with 5 different sizes and 3 different aspect ratios. 
    # Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios
#anchor_generator = AnchorGenerator(
#sizes=((32, 64, 128, 256, 512),),
#aspect_ratios=((0.5, 1.0, 2.0),)
#            )

#roi_pooler = torchvision.ops.MultiScaleRoIAlign(
#    featmap_names=['0'],
#    output_size=7, # industry standard for FRCNN
#    sampling_ratio=2
#        )







end = 0
os.chdir(r'C:\Users\mackm\Documents\Other\School\UNO\Semester 3\Forecasting\Project Git\econ8310-final-project')

for iteration in range(1):
    if end == 0:
        start = 0
    else:
        start = end 

    if iteration == 0:
        end = 5
    else:    
        end = (iteration +1) * 4
    
    print(f'{start}:{end}')


    class BaseballVideos(torch.utils.data.Dataset):
        def __init__(self, root=None, transforms=None):
            self.root = root
            self.transforms = transforms
            # load all image files, sorting them to
            # ensure that they are aligned
            if root==None:
                self.vids = list(sorted([os.path.join("Model Data", i) for i in os.listdir(os.path.join(os.path.curdir, "Model Data")) if '.mov' in i]))[start:end]
                self.notes = list(sorted([os.path.join("Model Data", i) for i in os.listdir(os.path.join(os.path.curdir, "Model Data")) if '.xml' in i]))[start:end]
                if len(self.vids)!=len(self.notes):
                    raise RuntimeError("Mismatch of annotation files and video files.\nPlease confirm that you have one annotation file for each video and try again.")
            imgs = []
            notes = []
            index = 0
            for i, k in zip(self.vids, self.notes):
                cap = cv.VideoCapture(i)
                note = minidom.parse(k)
                ret = True
                frame_count = 0
                print(index)
                index += 1
                while ret:
                    ret, frame = cap.read()
                    if ret:
                        frame_count += 1
                        frame = np.moveaxis(frame, -1, 0) # Pivot image so color channels first, then H then W
                        imgs.append(torch.from_numpy(frame).float()/255)
                        canvas_size = list(frame.shape[1:])

                    for f in range(frame_count):
                        frame_i = [j for j in note.getElementsByTagName("box") if int(j.attributes['frame'].value)==f]
                        boxes = []
                        labels = []
                        areas = []
                        movings = []

                        for j in frame_i:
                            attrs = j.getElementsByTagName('attribute')
                            #print(attrs[0])

                            if attrs is not None:
                                
                                moving = attrs[0].firstChild.data == 'true'
                            
                            else:
                                moving = False  # default if attribute is missing

                            print(moving)
                            if moving:
                                xtl = float(j.attributes['xtl'].value)
                                ytl = float(j.attributes['ytl'].value)
                                xbr = float(j.attributes['xbr'].value)
                                ybr = float(j.attributes['ybr'].value)
                                box = (xtl, ytl, xbr, ybr)

                                label = 1
                                area = (xbr - xtl) * (ybr - ytl)

                                boxes.append(box)
                                labels.append(label)
                                areas.append(area)
                                #movings.append(moving)

                        target = {}
                        print(len(boxes))
                        print(len(labels))
                        print(len(areas))
                        if len(boxes) > 0:
                            target["boxes"] = tv_tensors.BoundingBoxes(boxes, format="XYXY", canvas_size=canvas_size)
                            target["labels"] = labels
                            target["area"] = areas
                            #target["moving"] = movings
                        else:
                                target["boxes"] = torch.zeros((0, 4), dtype=torch.float32)
                                target["labels"] = torch.zeros((0,), dtype=torch.int64)
                                target['area'] = torch.zeros((0,), dtype=torch.float32)
                        print(target)
                        notes.append(target)
                 
            self.imgs = imgs
            self.notes = notes

                # target = {}
                # target["boxes"] = tv_tensors.BoundingBoxes(boxes, format="XYXY", canvas_size=F.get_size(img))
                # target["masks"] = tv_tensors.Mask(masks)
                # target["labels"] = labels
                # target["image_id"] = image_id
                # target["area"] = area
                # target["iscrowd"] = iscrowd
            self.imgs
            self.notes

        def __len__(self):
            return len(self.imgs)

        def __getitem__(self, idx):

            img = self.imgs[idx]
            target = self.notes[idx]

            if self.transforms is not None:
                img, target = self.transforms(img, target)

            return img, target

    dataset = BaseballVideos()
    #torch.save(data,f'dataset{iteration}.pt')
    
#TODO: move iteration loop to the NN

#cv2_imshow(frame)


# define training and validation data loaders




    
if iteration+1 in [4,8,13]:
    data_loader_test = torch.utils.data.DataLoader(
    dataset,
    batch_size=1,
    shuffle=False,
    collate_fn=collate_fn
     )
    BaseballNN.eval()
    with torch.no_grad():
        for images, targets in data_loader_test:
            images = [img for img in images]
            predictions = BaseballNN(images)
else: 
    
    
    data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=2,
    shuffle=True,
    collate_fn=collate_fn
      )
    BaseballNN.train()
    size = len(data_loader.dataset)
    for batch, (X, label) in enumerate(data_loader):
        pred = BaseballNN(X, label)
        loss = sum(loss for loss in pred.values())
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        if batch % 10 == 0:
            loss_val, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss_val:>7f}  [{current:>5d}/{size:>5d}]")
    #torch.save(BaseballNN.dict(),'baseball_model.pt')

del dataset, size, data_loader







#image code for later


#image = read_image("data/PennFudanPed/PNGImages/FudanPed00046.png")
#eval_transform = get_transform(train=False)



#image = (255.0 * (image - image.min()) / (image.max() - image.min())).to(torch.uint8)
#image = image[:3, ...]
#pred_labels = [f"pedestrian: {score:.3f}" for label, score in zip(pred["labels"], pred["scores"])]
#pred_boxes = pred["boxes"].long()
#output_image = draw_bounding_boxes(image, pred_boxes, pred_labels, colors="red")

#masks = (pred["masks"] > 0.7).squeeze(1)
#output_image = draw_segmentation_masks(output_image, masks, alpha=0.5, colors="blue")


#plt.figure(figsize=(12, 12))
#plt.imshow(output_image.permute(1, 2, 0))