# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COgZDWDO-SXffhp6GerEHbIc4yQ-7YbR
"""

# For reading data
import os
import numpy as np
from xml.dom import minidom

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# For visualizing
import plotly.express as px
from torchvision.io import read_image
from torchvision import tv_tensors
from torchvision.transforms.v2 import functional as F

# For model building
import torch
import torch.nn as nn

# for videos
import cv2 as cv


end = 0
for iteration in range(4):
    if end == 0:
        start = 0
    else:
        start = end 

    if iteration == 0:
        end = 13
    else:    
        end = (iteration +1) * 13
    
    print(f'{start}:{end}')


    class BaseballVideos(torch.utils.data.Dataset):
        def __init__(self, root=None, transforms=None):
            self.root = root
            self.transforms = transforms
            # load all image files, sorting them to
            # ensure that they are aligned
            if root==None:
                self.vids = list(sorted([os.path.join("Model Data", i) for i in os.listdir(os.path.join(os.path.curdir, "Model Data")) if '.mov' in i]))[start:end]
                self.notes = list(sorted([os.path.join("Model Data", i) for i in os.listdir(os.path.join(os.path.curdir, "Model Data")) if '.xml' in i]))[start:end]
                if len(self.vids)!=len(self.notes):
                    raise RuntimeError("Mismatch of annotation files and video files.\nPlease confirm that you have one annotation file for each video and try again.")
            imgs = []
            notes = []
            index = 0
            for i, k in zip(self.vids, self.notes):
                cap = cv.VideoCapture(i)
                note = minidom.parse(k)
                ret = True
                frame_count = 0
                print(index)
                index += 1
                while ret:
                    ret, frame = cap.read()
                    if ret:
                        frame_count += 1
                        frame = np.moveaxis(frame, -1, 0) # Pivot image so color channels first, then H then W
                        imgs.append(torch.from_numpy(frame))
                        canvas_size = list(frame.shape[1:])

                    for f in range(frame_count):
                        frame_i = [j for j in note.getElementsByTagName("box") if int(j.attributes['frame'].value)==f]
                        boxes = []
                        labels = []
                        areas = []
                        movings = []

                        for j in frame_i:
                            attrs = j.getElementsByTagName('attribute')


                            if attrs and attrs[0].firstChild is not None:
                                moving = attrs[0].firstChild.data == 'true'
                            
                            else:
                                moving = False  # default if attribute is missing

                                
                            if moving:
                                xtl = float(j.attributes['xtl'].value)
                                ytl = float(j.attributes['ytl'].value)
                                xbr = float(j.attributes['xbr'].value)
                                ybr = float(j.attributes['ybr'].value)
                                box = (xtl, ytl, xbr, ybr)

                                label = 'baseball'
                                area = (xbr - xtl) * (ybr - ytl)

                                boxes.append(box)
                                labels.append(label)
                                areas.append(area)
                                #movings.append(moving)

                        target = {}
                        target["boxes"] = tv_tensors.BoundingBoxes(boxes, format="XYXY", canvas_size=canvas_size)
                        target["labels"] = labels
                        target["area"] = areas
                        #target["moving"] = movings

                        notes.append(target)
                 
            self.imgs = imgs
            self.notes = notes

                # target = {}
                # target["boxes"] = tv_tensors.BoundingBoxes(boxes, format="XYXY", canvas_size=F.get_size(img))
                # target["masks"] = tv_tensors.Mask(masks)
                # target["labels"] = labels
                # target["image_id"] = image_id
                # target["area"] = area
                # target["iscrowd"] = iscrowd
            self.imgs
            self.notes

        def __len__(self):
            return len(self.imgs)

        def __getitem__(self, idx):

            img = self.imgs[idx]
            target = self.notes[idx]

            if self.transforms is not None:
                img, target = self.transforms(img, target)

            return img, target

    data = BaseballVideos()
    torch.save(data,f'dataset{iteration}.pt')

#TODO: move iteration loop to the NN

#cv2_imshow(frame)

import torchvision
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.rpn import AnchorGenerator


class BaseballNN():
    def __init__(self): 
        # load a pre-trained model for classification and return only the features
        backbone = torchvision.models.mobilenet_v2(weights="DEFAULT").features
        #mobilenet_v2 output channels are 1280
        backbone.out_channels = 1280

        
        # RPN generate 5 x 3 anchors per spatial location, with 5 different sizes and 3 different aspect ratios. 
        # Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios
        anchor_generator = AnchorGenerator(
            sizes=((32, 64, 128, 256, 512),),
            aspect_ratios=((0.5, 1.0, 2.0),)
        )

        roi_pooler = torchvision.ops.MultiScaleRoIAlign(
            featmap_names=['0'],
            output_size=7, # industry standard for FRCNN
            sampling_ratio=2
        )

        self.model = FasterRCNN(
            backbone,
            num_classes=2, #num_classes: 1=moving ball, 0 = no moving ball
            rpn_anchor_generator=anchor_generator,
            box_roi_pool=roi_pooler
        )

    def get_model(self):
        return self.model





